# Generated by Django 2.1.5 on 2019-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=30)),
                ('person_phone', models.CharField(max_length=30)),
                ('other_number', models.CharField(max_length=20)),
                ('event_date', models.CharField(max_length=30)),
                ('event_time', models.CharField(max_length=30)),
                ('event_city', models.CharField(max_length=30)),
                ('event_landmark', models.CharField(max_length=50)),
                ('event_address', models.CharField(max_length=200)),
            ],
        ),
    ]
