# Generated by Django 2.1.5 on 2019-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('vote', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='fullSite/image')),
                ('date', models.DateField()),
            ],
        ),
    ]
