# Generated by Django 2.1.5 on 2019-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0003_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
