# Generated by Django 2.1.5 on 2019-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0005_auto_20190626_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateField(default='1999-11-23'),
        ),
    ]
