# Generated by Django 2.1.5 on 2019-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0006_auto_20190626_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderBook',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('personname', models.CharField(max_length=30)),
                ('personphone', models.CharField(max_length=30)),
                ('othernumber', models.CharField(max_length=20)),
                ('eventdate', models.CharField(max_length=30)),
                ('eventtime', models.CharField(max_length=30)),
                ('eventcity', models.CharField(max_length=30)),
                ('eventlandmark', models.CharField(max_length=50)),
                ('eventaddress', models.CharField(max_length=200)),
            ],
        ),
    ]
