# Generated by Django 2.1.5 on 2019-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0007_orderbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneyRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedBy', models.CharField(max_length=30)),
                ('orderId', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to='fullSite/image')),
                ('image2', models.ImageField(upload_to='fullSite/image')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
