# Generated by Django 2.1.5 on 2019-06-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0008_moneyrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('quary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=300)),
            ],
        ),
    ]
