# Generated by Django 2.1.5 on 2019-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0010_auto_20190701_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
