# Generated by Django 2.1.5 on 2019-07-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0011_account_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='landmark',
        ),
    ]
