# Generated by Django 2.1.5 on 2019-07-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullSite', '0013_auto_20190704_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='completedBy',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
